on:
  push:
    branches:
      - master

jobs:
  build-mac:
    name: Mac executable
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release --all-features
      - run: cargo test
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: directory-packages-props-converter-mac
          path: target/release/directory-packages-props-converter

  build-windows:
    name: Windows executable
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release --all-features
      - run: cargo test
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: directory-packages-props-converter-win.exe
          path: target/release/directory-packages-props-converter.exe

  release:
    permissions: write-all
    name: Release
    runs-on: ubuntu-latest
    needs: [build-mac, build-windows]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Get version from CHANGELOG.md
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          path: ./CHANGELOG.md

      - uses: actions/download-artifact@v3
        with:
          name: directory-packages-props-converter-mac
          path: .

      - uses: actions/download-artifact@v3
        with:
          name: directory-packages-props-converter-win.exe
          path: .

      - name: Push a tag
        id: push_tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.changelog_reader.outputs.version }}
          release_branches: master

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.changelog_reader.outputs.changes }}
          tag_name: v${{ steps.changelog_reader.outputs.version }}
          name: ${{ steps.changelog_reader.outputs.version }}
          files: |
            directory-packages-props-converter.exe
            directory-packages-props-converter
            LICENSE